# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-04-13 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('phone', models.ImageField(max_length=45, upload_to='')),
                ('college', models.CharField(max_length=45)),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
